"""add_new_features

Revision ID: 5377338f4f59
Revises: 
Create Date: 2026-05-15 08:26:10.546070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5377338f4f59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('issue_id', sa.CHAR(length=32), nullable=False),
    sa.Column('suggestion_text', sa.TEXT(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('model_used', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('severity', sa.INTEGER(), nullable=False),
    sa.Column('is_anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('submitter_id', sa.CHAR(length=32), nullable=False),
    sa.Column('assigned_to', sa.CHAR(length=32), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('resolution_note', sa.TEXT(), nullable=True),
    sa.Column('attachment_urls', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('actor_id', sa.CHAR(length=32), nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_id', sa.CHAR(length=32), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('event_meta', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_posts',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('severity_score', sa.FLOAT(), nullable=False),
    sa.Column('reaction_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievements',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('verified_by', sa.CHAR(length=32), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_status_history',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('issue_id', sa.CHAR(length=32), nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('changed_by', sa.CHAR(length=32), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('jti', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('revoked_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('notifications',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('ref_id', sa.CHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('department', sa.VARCHAR(length=128), nullable=True),
    sa.Column('position', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=64), nullable=True),
    sa.Column('supabase_uid', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('impact_score', sa.FLOAT(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supabase_uid')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('messages',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('room_id', sa.CHAR(length=32), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('employee_id', sa.CHAR(length=32), nullable=False),
    sa.Column('participant_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type', 'employee_id', 'participant_id', name='uq_room_participants')
    )
    op.create_table('mentorship_sessions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('mentor_id', sa.CHAR(length=32), nullable=True),
    sa.Column('employee_id', sa.CHAR(length=32), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reactions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('post_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['public_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_reaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reactions')
    op.drop_table('mentorship_sessions')
    op.drop_table('chat_rooms')
    op.drop_table('messages')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_table('token_blacklist')
    op.drop_table('issue_status_history')
    op.drop_table('achievements')
    op.drop_table('public_posts')
    op.drop_table('audit_logs')
    op.drop_table('issues')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
